### ISSUE TITLE
$HOME?

### ISSUE THREAD

**Issue by Daniel15** [juliavallina/windows-zsh-theme#1]
If you want it to look as Windows-ish as possible, what about replacing `C:\$HOME` with `C:\Users\{username}`? 😛

**Comment by juliavallina** [comment]
Hi Daniel,
Thank you for your comment.
You are completely right. It would be more accurate with `C:\Users\{username}` and I've tried it.
But I found it annoyingly long, so I end up with the `$HOME` version.
Anyway, it's a theme just for fun and for me. 
If you want the `C:\Users\{username}` I'll be happy to help you with it.
