### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [juliavallina/windows-zsh-theme#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by juliavallina** [comment]
Hi @unixorn , thanks for the interest and for this issue.

I have just added a LICENSE file as you suggested.

Feel free to include this theme on your repository. It will be an honor for me

**Comment by unixorn** [comment]
Thanks, adding it today.
